sigma1 = 1.0;
sigma2 = 2.0;
[x y] = meshgrid(-2:2,-2:2);
F1=(1/(2*pi*sigma1^2))*exp(-((x.^2+y.^2)/(2*sigma1^2)));
F1=F1./sum(F1(:));
F2=(1/(2*pi*sigma2^2))*exp(-((x.^2+y.^2)/(2*sigma2^2)));
F2=F2./sum(F2(:));
figure('name','Filter 1');
mesh(F1);
figure('name','Filter 2');
mesh(F2);
I = imread('ntugn.jpg');
figure('name','Original Image with Gaussian Noise');
imshow(I);
G1 = uint8(conv2(I,F1));
figure('name','Image1 after using Filter 1');
imshow(G1);
G2 = uint8(conv2(I,F2));
figure('name','Image1 after using Filter 2');
imshow(G2);
J = imread('ntusp.jpg');
figure('name','Original Image with Speckle Noise');
imshow(J);
H1 = uint8(conv2(J,F1));
figure('name','Image2 after using Filter 1');
imshow(H1);
H2 = uint8(conv2(J,F2));
figure('name','Image2 after using Filter 2');
imshow(H2);